/**
 * Migrate `<target>/src/WeeblyExport/` into the new Firebase-project layout.
 *
 * What it does:
 *   - Copies WeeblyExport/styles/*.less    → src/less/
 *   - Copies WeeblyExport/assets/*.js      → src/js/
 *   - Generates skeleton `.kit` files in src/html/ matching the standard
 *     Q42-style pattern (_head, _footer, _nav, _gdpr, index, 404, impressum,
 *     datenschutz, kontakt). Each skeleton references the Weebly source so
 *     porting is a copy-paste-port loop, not a guess.
 *   - Moves src/WeeblyExport → reference/WeeblyExport so `src/` becomes
 *     the new source of truth.
 *
 * Why skeletons instead of auto-converting partials:
 *   Weebly partials are Mustache (`{logo}`, `{{#sections}}…`), CodeKit `.kit`
 *   files use `<!-- @include _head.kit -->`. A half-converted file is worse
 *   than a clean skeleton with the reference one click away.
 *
 * Idempotent: skips files that already exist; never overwrites.
 *
 * Standalone:
 *   node ~/Work\ Files/Weebly-to-Firebase/convert-assets.mjs [target]
 * Defaults `target` to process.cwd().
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { askYesNo, close } from './lib/prompt.mjs';
import { resolveTarget } from './lib/target.mjs';

/** Standard page set, mirroring Q42's src/html/ shape. */
const PAGES = ['index', '404', 'impressum', 'datenschutz', 'kontakt'];
const PARTIALS = ['_head', '_nav', '_footer', '_gdpr'];

async function exists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

/** Copy file only if dest doesn't already exist (idempotent). */
async function copyIfMissing(src, dest, label) {
  if (await exists(dest)) {
    console.log(`  skip ${label} (exists)`);
    return false;
  }
  await ensureDir(path.dirname(dest));
  await fs.copyFile(src, dest);
  console.log(`  +    ${label}`);
  return true;
}

/** Copy all files matching `filter` from a dir into another. Flat copy. */
async function copyTree(srcDir, destDir, filter, labelPrefix) {
  if (!(await exists(srcDir))) {
    console.log(`  (no ${srcDir} — skipping ${labelPrefix})`);
    return;
  }
  const entries = await fs.readdir(srcDir, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isFile() || !filter(e.name)) continue;
    await copyIfMissing(
      path.join(srcDir, e.name),
      path.join(destDir, e.name),
      `${labelPrefix}/${e.name}`,
    );
  }
}

/**
 * Write a starter .kit partial. The body is intentionally minimal — the porter
 * will paste from the referenced Weebly source. Each TODO points at the file
 * to read.
 */
async function writeSkeletonKit(root, name, reference) {
  const dest = path.join(root, 'src/html', `${name}.kit`);
  if (await exists(dest)) {
    console.log(`  skip src/html/${name}.kit (exists)`);
    return;
  }
  const isPartial = name.startsWith('_');
  const body = isPartial
    ? `<!-- ${name}.kit — partial -->
<!-- TODO: port from ${reference} -->
`
    : `<!-- ${name}.kit — page -->
<!DOCTYPE html>
<html lang="de">
<!-- @include _head.kit -->
<body class="${name}-page">
  <!-- @include _gdpr.kit -->
  <!-- @include _nav.kit -->

  <main>
    <!-- TODO: port content from ${reference} -->
  </main>

  <!-- @include _footer.kit -->
</body>
</html>
`;
  await ensureDir(path.dirname(dest));
  await fs.writeFile(dest, body);
  console.log(`  +    src/html/${name}.kit`);
}

/**
 * Write a main.less that @imports everything copied from WeeblyExport/styles.
 * Only created if it doesn't already exist. Order roughly matches Weebly's own
 * convention (variables → resets → ui → page types).
 */
async function writeMainLess(root) {
  const dest = path.join(root, 'src/less/main.less');
  if (await exists(dest)) {
    console.log('  skip src/less/main.less (exists)');
    return;
  }
  const order = [
    'variables', 'variables_light',
    '_resets', '_global', '_ui-kit', '_nav',
    '_page-types', '_blog', '_commerce', '_gdpr',
    '_responsive',
  ];
  const lessDir = path.join(root, 'src/less');
  const present = new Set(
    (await exists(lessDir) ? await fs.readdir(lessDir) : []).filter(f => f.endsWith('.less')),
  );
  const lines = order
    .filter(name => present.has(`${name}.less`))
    .map(name => `@import "${name}.less";`);
  const body = `// main.less — entry point for the LESS build.
// Generated by Weebly-to-Firebase from WeeblyExport/styles/.
// Edit freely; this file is not regenerated on re-runs.

${lines.join('\n')}
`;
  await fs.writeFile(dest, body);
  console.log('  +    src/less/main.less');
}

/** Move src/WeeblyExport → reference/WeeblyExport. No-op if already moved. */
async function moveWeeblyToReference(root) {
  const fromPath = path.join(root, 'src/WeeblyExport');
  const toPath = path.join(root, 'reference/WeeblyExport');
  if (!(await exists(fromPath))) {
    console.log('  (src/WeeblyExport already moved or absent)');
    return;
  }
  if (await exists(toPath)) {
    console.log('  reference/WeeblyExport already exists — leaving src/WeeblyExport in place.');
    console.log('  Remove one of them manually if you want them merged.');
    return;
  }
  await ensureDir(path.dirname(toPath));
  await fs.rename(fromPath, toPath);
  console.log('  moved src/WeeblyExport → reference/WeeblyExport');
}

export async function run({ root, interactive = true } = {}) {
  if (!root) root = resolveTarget(process.argv.slice(2));

  const weeblySrc = path.join(root, 'src/WeeblyExport');
  const weeblyRef = path.join(root, 'reference/WeeblyExport');

  if (!(await exists(weeblySrc)) && !(await exists(weeblyRef))) {
    console.log(`No WeeblyExport found at src/WeeblyExport or reference/WeeblyExport (in ${root}) — nothing to convert.`);
    return;
  }

  // The export may already have been moved on a prior run; copy from wherever
  // it currently lives.
  const sourceRoot = (await exists(weeblySrc)) ? weeblySrc : weeblyRef;

  console.log(`\nConvert Weebly assets in ${root}:`);
  const doStyles = !interactive || await askYesNo('  Copy WeeblyExport/styles/*.less → src/less/?', true);
  const doJs     = !interactive || await askYesNo('  Copy WeeblyExport/assets/*.js   → src/js/?',   true);
  const doKits   = !interactive || await askYesNo('  Generate starter .kit partials in src/html/?', true);
  const doMove   = !interactive || await askYesNo('  Move src/WeeblyExport → reference/WeeblyExport when done?', true);

  if (doStyles) {
    console.log('\n→ LESS');
    await copyTree(
      path.join(sourceRoot, 'styles'),
      path.join(root, 'src/less'),
      f => f.endsWith('.less'),
      'src/less',
    );
    await writeMainLess(root);
  }

  if (doJs) {
    console.log('\n→ JS');
    await copyTree(
      path.join(sourceRoot, 'assets'),
      path.join(root, 'src/js'),
      f => f.endsWith('.js'),
      'src/js',
    );
  }

  if (doKits) {
    console.log('\n→ .kit skeletons');
    for (const p of PARTIALS) {
      const ref = p === '_nav'    ? 'reference/WeeblyExport/partials/navigation/list.tpl'
                : p === '_gdpr'   ? 'reference/WeeblyExport/styles/_gdpr.less + header.html'
                : p === '_head'   ? 'reference/WeeblyExport/header.html (head block)'
                :                   'reference/WeeblyExport/header.html (footer block)';
      await writeSkeletonKit(root, p, ref);
    }
    for (const p of PAGES) {
      const ref = p === 'index'
        ? 'reference/WeeblyExport/header.html (body composition)'
        : `reference/WeeblyExport/no-header.html (use as base for ${p})`;
      await writeSkeletonKit(root, p, ref);
    }
  }

  if (doMove) {
    console.log('\n→ relocate');
    await moveWeeblyToReference(root);
  }

  console.log('\nDone.');
}

// Standalone entry point.
if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    await run({ interactive: true });
  } finally {
    close();
  }
}
