/**
 * `weebly-to-firebase convert` — migrate reference/WeeblyExport/ into src/.
 *
 * What it does:
 *   - Copies WeeblyExport/styles/*.less    → src/less/
 *   - Copies WeeblyExport/assets/*.js      → src/js/
 *   - Generates skeleton `.html` files in src/html/ matching the standard
 *     Q42-style pattern. Partials use the Sass-style `_` prefix
 *     (`_meta.html`, `_nav.html`, etc.) and are composed via posthtml-include
 *     (`<include src="_meta.html"></include>`). Each skeleton references the
 *     Weebly source so porting is a copy-paste-port loop, not a guess.
 *
 * The export lives in `reference/WeeblyExport/` from the start — it's source
 * material to read from, not project source. (Older projects scaffolded with
 * `src/WeeblyExport/` still work: convert falls back to that location.)
 *
 * Why skeletons instead of auto-converting partials:
 *   Weebly partials are Mustache (`{logo}`, `{{#sections}}…`) — different
 *   semantics from posthtml-include's tag-based composition. A half-converted
 *   file is worse than a clean skeleton with the reference one click away.
 *
 * Each step has a --skip-* flag to opt out individually.
 * Idempotent: skips files that already exist; never overwrites.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { askYesNo } from '../lib/prompt.mjs';
import { resolveTarget } from '../lib/target.mjs';

/**
 * Standard page set, mirroring Q42's src/html/ shape.
 * Partials use the Sass-convention `_` prefix so the posthtml-cli build glob
 * (`src/html/[!_]*.html`) can pick up pages while ignoring partials.
 */
const PAGES = ['index', '404', 'impressum', 'datenschutz', 'kontakt'];
const PARTIALS = ['_meta', '_nav', '_footer', '_gdpr'];

async function exists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

/** Copy file only if dest doesn't already exist (idempotent). */
async function copyIfMissing(src, dest, label) {
  if (await exists(dest)) {
    console.log(`  skip ${label} (exists)`);
    return false;
  }
  await ensureDir(path.dirname(dest));
  await fs.copyFile(src, dest);
  console.log(`  +    ${label}`);
  return true;
}

/** Copy all files matching `filter` from a dir into another. Flat copy. */
async function copyTree(srcDir, destDir, filter, labelPrefix) {
  if (!(await exists(srcDir))) {
    console.log(`  (no ${srcDir} — skipping ${labelPrefix})`);
    return;
  }
  const entries = await fs.readdir(srcDir, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isFile() || !filter(e.name)) continue;
    await copyIfMissing(
      path.join(srcDir, e.name),
      path.join(destDir, e.name),
      `${labelPrefix}/${e.name}`,
    );
  }
}

/**
 * Write a starter .html partial or page. The body is intentionally minimal —
 * the porter will paste from the referenced Weebly source. Each TODO names
 * the file to read.
 *
 * Partials are detected by the Sass-style `_` prefix. Page templates compose
 * partials via posthtml-include's `<include src="…"></include>` tag — resolved
 * against `src/html/` per the project's `.posthtmlrc.js` config.
 */
async function writeSkeletonHtml(root, name, reference) {
  const dest = path.join(root, 'src/html', `${name}.html`);
  if (await exists(dest)) {
    console.log(`  skip src/html/${name}.html (exists)`);
    return;
  }
  const isPartial = name.startsWith('_');
  const body = isPartial
    ? `<!-- ${name}.html — partial -->
<!-- TODO: port from ${reference} -->
`
    : `<!-- ${name}.html — page -->
<!DOCTYPE html>
<html lang="de">
<head>
  <include src="_meta.html"></include>
</head>
<body class="${name}-page">
  <include src="_gdpr.html"></include>
  <include src="_nav.html"></include>

  <main>
    <!-- TODO: port content from ${reference} -->
  </main>

  <include src="_footer.html"></include>
</body>
</html>
`;
  await ensureDir(path.dirname(dest));
  await fs.writeFile(dest, body);
  console.log(`  +    src/html/${name}.html`);
}

/**
 * Write a main.less that @imports everything copied from WeeblyExport/styles.
 * Only created if it doesn't already exist. Order roughly matches Weebly's own
 * convention (variables → resets → ui → page types).
 */
async function writeMainLess(root) {
  const dest = path.join(root, 'src/less/main.less');
  if (await exists(dest)) {
    console.log('  skip src/less/main.less (exists)');
    return;
  }
  const order = [
    'variables', 'variables_light',
    '_resets', '_global', '_ui-kit', '_nav',
    '_page-types', '_blog', '_commerce', '_gdpr',
    '_responsive',
  ];
  const lessDir = path.join(root, 'src/less');
  const present = new Set(
    (await exists(lessDir) ? await fs.readdir(lessDir) : []).filter(f => f.endsWith('.less')),
  );
  const lines = order
    .filter(name => present.has(`${name}.less`))
    .map(name => `@import "${name}.less";`);
  const body = `// main.less — entry point for the LESS build.
// Generated by weebly-to-firebase from WeeblyExport/styles/.
// Edit freely; this file is not regenerated on re-runs.

${lines.join('\n')}
`;
  await fs.writeFile(dest, body);
  console.log('  +    src/less/main.less');
}

export async function run(flags = {}) {
  const root = resolveTarget(flags.target);
  const autoAccept = !!flags.yes;

  const weeblyRef = path.join(root, 'reference/WeeblyExport');
  const weeblySrc = path.join(root, 'src/WeeblyExport');

  if (!(await exists(weeblyRef)) && !(await exists(weeblySrc))) {
    console.log(`No WeeblyExport found at reference/WeeblyExport or src/WeeblyExport (in ${root}) — nothing to convert.`);
    return;
  }

  // reference/WeeblyExport is the canonical drop location; fall back to
  // src/WeeblyExport for any project scaffolded under the old layout.
  const sourceRoot = (await exists(weeblyRef)) ? weeblyRef : weeblySrc;

  console.log(`\nConvert Weebly assets in ${root}:`);

  // Per-step decision: explicit --skip-* flag wins; otherwise ask (or accept
  // default under --yes).
  const doStyles = flags.skipStyles ? false : await askYesNo(
    '  Copy WeeblyExport/styles/*.less → src/less/?', { default: true, autoAccept });
  const doJs = flags.skipJs ? false : await askYesNo(
    '  Copy WeeblyExport/assets/*.js   → src/js/?',   { default: true, autoAccept });
  const doHtml = flags.skipHtml ? false : await askYesNo(
    '  Generate starter .html partials in src/html/?', { default: true, autoAccept });

  if (doStyles) {
    console.log('\n→ LESS');
    await copyTree(
      path.join(sourceRoot, 'styles'),
      path.join(root, 'src/less'),
      f => f.endsWith('.less'),
      'src/less',
    );
    await writeMainLess(root);
  }

  if (doJs) {
    console.log('\n→ JS');
    await copyTree(
      path.join(sourceRoot, 'assets'),
      path.join(root, 'src/js'),
      f => f.endsWith('.js'),
      'src/js',
    );
  }

  if (doHtml) {
    console.log('\n→ .html skeletons');
    for (const p of PARTIALS) {
      const ref = p === '_nav'    ? 'reference/WeeblyExport/partials/navigation/list.tpl'
                : p === '_gdpr'   ? 'reference/WeeblyExport/styles/_gdpr.less + header.html'
                : p === '_meta'   ? 'reference/WeeblyExport/header.html (head meta tags)'
                :                   'reference/WeeblyExport/header.html (footer block)';
      await writeSkeletonHtml(root, p, ref);
    }
    for (const p of PAGES) {
      const ref = p === 'index'
        ? 'reference/WeeblyExport/header.html (body composition)'
        : `reference/WeeblyExport/no-header.html (use as base for ${p})`;
      await writeSkeletonHtml(root, p, ref);
    }
  }

  console.log('\nDone.');
}
