/**
 * `app.js` entry-point composition — shared by `convert` (first-time scaffold)
 * and `port` (refresh).
 *
 * Order:
 *   1. Vendor / framework / plugins first (jQuery and its plugins must be
 *      loaded before code that depends on them).
 *   2. Anything else in alphabetical order.
 *   3. Site-specific / custom code last so it can rely on everything above.
 *
 * Side-effect imports (`import './plugins.js';`) — Weebly's JS is classic
 * IIFE-wrapped script, not ESM. Rollup happily treats them as modules with
 * no exports and inlines them inside the IIFE bundle.
 */

const FIRST = ['plugins.js', 'vendor.js', 'jquery.js', 'theme.js', 'gdpr.js'];
const LAST = ['custom.js', 'site.js', 'main.js'];

/** Matches comment header w2f writes; used to detect "safe to regenerate". */
export const APP_JS_MARKER = /Generated by (?:weebly-to-firebase|w2f)/i;

/**
 * @param {Iterable<string>} presentFilenames — `.js` file basenames in src/js/
 * @returns {string[]} filenames in import order, excluding `app.js` itself.
 */
export function composeAppImports(presentFilenames) {
  const present = new Set(presentFilenames);
  present.delete('app.js'); // never self-import
  const firstHits = FIRST.filter(f => present.has(f));
  const lastHits  = LAST.filter(f => present.has(f));
  const taken = new Set([...firstHits, ...lastHits]);
  const middle = [...present].filter(f => !taken.has(f)).sort();
  return [...firstHits, ...middle, ...lastHits];
}
