/**
 * main.less import composition — shared by `convert` (first-time scaffold)
 * and `port` (refresh). Both callers want the same order, so keep the rules
 * in one place.
 *
 * Order:
 *   1. Every `variables*.less` file present, sorted alphabetically. Base
 *      `variables.less` lands first; theme variants (`variables_dark`,
 *      `variables_light`, …) follow and override. LESS's last-wins rule
 *      means whichever variant sorts last governs the final palette — for
 *      Weebly's Unite theme that's `variables_light`, which matches the
 *      typical default.
 *   2. `_fonts` next so any @font-face is defined before usage.
 *   3. The canonical Weebly partial chain — only files that actually exist
 *      on disk get an `@import`.
 *
 * Custom files the user drops in alongside (e.g. `_brand.less`) are NOT
 * pulled in — they belong below the canonical block in a hand-edited
 * main.less.
 */

const PARTIALS = [
  '_fonts',
  '_resets', '_global', '_ui-kit', '_nav',
  '_page-types', '_blog', '_commerce', '_gdpr',
  '_responsive',
];

/**
 * The partial w2f writes stubs into when a referenced variable isn't defined
 * anywhere on disk. Imported between variables and the canonical partials so
 * the rest of the chain can resolve those names.
 */
export const W2F_STUBS_NAME = '_w2f-undefined';

/**
 * Prefix for files `port` dumps directly from the wget mirror (compiled
 * stylesheets, raw CSS). They land between variables/stubs and the canonical
 * partials so that structured Weebly-source partials (from `convert`) override
 * the dump when both are present. The intended workflow: dump first, then
 * progressively replace with cleaner source. Sorted alphabetically among
 * themselves — the order of competing dump files doesn't typically matter.
 */
export const W2F_DUMP_PREFIX = '_w2f-';

/** Matches comment headers w2f writes; used to detect "safe to regenerate". */
export const MAIN_LESS_MARKER = /Generated by (?:weebly-to-firebase|w2f)/i;

/**
 * Stable basename for a mirror-dumped stylesheet. Anything weebly-ish (URL
 * cache busters, scheme, query string) is stripped so the file lands as a
 * clean LESS partial regardless of what the source URL looked like.
 *
 * @param {string} url — absolute or relative stylesheet URL
 * @returns {string} `_w2f-<slug>` (no extension), suitable for use as a
 *                   partial name in src/less/.
 */
export function dumpStylesheetName(url) {
  let path = url;
  try { path = new URL(url, 'https://x/').pathname; } catch { /* keep raw */ }
  let last = path.split('/').filter(Boolean).pop() || 'styles';
  try { last = decodeURIComponent(last); } catch { /* keep encoded */ }
  // Strip query/fragment, the .css/.less extension, then slugify.
  const stem = last.split(/[?#]/)[0]
    .replace(/\.(?:css|less)$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'styles';
  return `${W2F_DUMP_PREFIX}${stem}`;
}

/**
 * @param {Iterable<string>} presentFilenames — `.less` file basenames in src/less/
 * @returns {string[]} import names (no extension), in canonical order, only
 *                     including files actually present.
 */
export function composeMainImports(presentFilenames) {
  const present = presentFilenames instanceof Set
    ? presentFilenames
    : new Set(presentFilenames);
  const variables = [...present]
    .filter(f => /^variables[a-z0-9_-]*\.less$/i.test(f))
    .sort()
    .map(f => f.replace(/\.less$/i, ''));
  const stubs = present.has(`${W2F_STUBS_NAME}.less`) ? [W2F_STUBS_NAME] : [];
  // Mirror-dumped stylesheets — anything with the _w2f- prefix that isn't the
  // stubs file or _w2f-undefined. Sorted so successive ports stay stable.
  const dumps = [...present]
    .filter(f => f.startsWith(W2F_DUMP_PREFIX)
      && f !== `${W2F_STUBS_NAME}.less`
      && f.endsWith('.less'))
    .sort()
    .map(f => f.replace(/\.less$/i, ''))
    .filter(name => name !== W2F_STUBS_NAME);
  const partials = PARTIALS.filter(name => present.has(`${name}.less`));
  return [...variables, ...stubs, ...dumps, ...partials];
}

/* ──────────────────────────────────────────────────────────────────────────
 * Undefined-variable detection
 *
 * Weebly's editor injects some variables at theme-edit time (`@shade`,
 * `@text`, etc.) that never make it into the static export. The static
 * LESS files reference them, so a fresh-from-export build fails on
 * undefined-variable errors. We scan the source files, find anything used
 * but not defined, and let the caller emit a stub file so the build can
 * succeed while the user fills in real values.
 * ────────────────────────────────────────────────────────────────────────── */

// Standard LESS / CSS at-rules. `@import`, `@media`, etc. look like variable
// references to a naive regex; this set lets us skip them.
const LESS_AT_RULE_KEYWORDS = new Set([
  'import', 'media', 'font-face', 'keyframes', 'charset', 'supports',
  'page', 'document', 'namespace', 'viewport', 'counter-style',
  'font-feature-values', 'container', 'layer', 'scope', 'starting-style',
  'property', '-webkit-keyframes', '-moz-keyframes', '-ms-viewport',
]);

const VAR_DEF_RE = /^\s*@([a-zA-Z_][\w-]*)\s*:/gm;
const VAR_USE_RE = /@([a-zA-Z_][\w-]*)\b/g;

// `.mixin-name(@param, @other: default) {` — captures the parens body so we
// can pull @-prefixed parameter names out of it. LESS mixin params are
// locally scoped; without recognising them they'd look "undefined".
const MIXIN_PARAM_BLOCK_RE = /[.#][a-zA-Z_][\w-]*\s*\(([^)]*)\)\s*\{/g;

/**
 * @param {Array<{name: string, content: string}>} files
 * @returns {string[]} variable names (without leading @) that are referenced
 *                     by any file but defined by none. Sorted alphabetically.
 *
 * Definition sources counted:
 *   - top-level `@var: …;` statements (the regex is anchored to line-start
 *     but applies to nested rules too since LESS lets vars be redefined
 *     anywhere)
 *   - mixin parameter names (`.mixin(@param)` — locally scoped, but they
 *     resolve at use-site so we treat them as defined globally).
 */
export function findUndefinedVariables(files) {
  const defs = new Set();
  const uses = new Set();
  for (const { content } of files) {
    for (const m of content.matchAll(VAR_DEF_RE)) defs.add(m[1]);
    for (const block of content.matchAll(MIXIN_PARAM_BLOCK_RE)) {
      for (const p of block[1].matchAll(/@([a-zA-Z_][\w-]*)/g)) defs.add(p[1]);
    }
    for (const m of content.matchAll(VAR_USE_RE)) {
      const v = m[1];
      if (LESS_AT_RULE_KEYWORDS.has(v)) continue;
      uses.add(v);
    }
  }
  return [...uses].filter(v => !defs.has(v)).sort();
}
